apiVersion: v1
kind: Service
metadata:
  name: backendlb
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: app-backend 
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-connection
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
