apiVersion: v1
kind: PersistentVolume
metadata:
  name: localpv
  labels:
    type: localpv
spec:
  storageClassName: projetok8-pv
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /meubanco/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localpvc
spec:
  storageClassName: projetok8-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
